#!/bin/bash
### lantern:
### modular and automated pen-testing enumeration and reporting tool
### author: J4CKD4W

### GRAB ROOTDIR AND PATH VARS
. "$(cd -- "$(dirname -- "$(readlink -f -- "${BASH_SOURCE[0]}")")" >/dev/null 2>&1 && pwd)/lib/pathfinder"
. "$ROOTDIR/lib/messages"
. "$ROOTDIR/lib/args"
. "$CONFIG"

### HANDLE ARGUMENTS AND FLAGS
parseargs "$@"

case "$ACTION" in
  help)    argshelp; exit 0 ;;
  version) argsversion; exit 0 ;;
  config)  nano "$CONFIG"; exit 0 ;;
  error)   fail "${RED}Error:${END} $ARGSERR" >&2; exit 2 ;;
  run)     : ;;
esac

### CHECK WHETHER THIS IS FIRST RUN AND DEPENDENCIES WERE ALREADY CHECKED
if [ "$INIT" -eq 1 ] || [ "$DEPCHECK" -eq 0 ]; then
  "$SCRIPTDIR/bootstrap"
fi
