#!/bin/bash

# Resolve helper dir (modules) relative to this script, works via symlink
ROOTDIR=$rootdir
LIBDIR="$(cd -- "$ROOTDIR/lib" && pwd -P)"
MODDIR="$(cd -- "$ROOTDIR/modules" && pwd -P)"
LISTDIR="$(cd -- "$ROOTDIR/lists" && pwd -P)"
SCRIPTDIR="$(cd -- "$ROOTDIR/scripts" && pwd -P)"
